### ISSUE TITLE
Which version to use for DPG tutorial

### ISSUE THREAD

**Issue by JNmpi** [pyiron/pyiron_workflow#207]
For our upcoming tutorial at the DPG meeting, we have to build and test the workflow examples next week. There will be a hard deadline of March 4 to have all packages, notebooks etc. together and to allow MPCDF to set up the infrastructure and container. For this reason, @srmnitc and I will come together next week to discuss the best strategy to bring a previous example related to nanoindentation analysis into pyiron_workflows. @liamhuber and @jan-janssen, it would be great if you could advise us which version to use, keeping the hard time constraints in mind.

**Comment by liamhuber** [comment]
Once I have #160 passing tests, I'll merge it and release 0.3.0 -- later today or Tuesday? I think this then will be sufficient for the DPG, just needing "content" (i.e. specific nodes -- some of which we might migrate into the standard node package later). Monday is a public holiday here, but other than that I'll try to be super responsive next week in case we need any patches to accommodate DPG needs.

**Comment by liamhuber** [comment]
@JNmpi, @srmnitc, I just released 0.3.0 -- should be available on conda in a little while. All the storage features (and thus putting a workflow in job) only work on python 3.11 due to restrictions in `h5io` and `h5io_browser`, but I don't imagine that's a big barrier.

My best current understanding is that this version should be sufficient for running the demos you want to run and it's just a matter of writing new nodes, but if there's a serious roadblock we still have enough time to iterate the version again.
