### ISSUE TITLE
Macro node syntax - node dependency without explicitly specifying output channel

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_workflow#392]
My problem (a minor one, but still annoying from the perspective of a user)

Consider the vasp job that I'm running here:

```python
import os
import shutil
import subprocess
from pyiron_workflow import Workflow
from ase.build import bulk
from pymatgen.io.ase import AseAtomsAdaptor
from pyiron_atomistics.vasp.output import parse_vasp_output as pvo
from pymatgen.io.vasp.outputs import Vasprun

def is_line_in_file(filepath, line, exact_match=True):
    try:
        with open(filepath, "r") as file:
            for file_line in file:
                if exact_match and line == file_line.strip():
                    return True
                elif not exact_match and line in file_line:
                    return True
    except FileNotFoundError:
        print(f"File '{filepath}' not found.")
    return False

@Workflow.wrap.as_function_node("output_dict")
def parse_VaspOutput(workdir: str, output) -> dict:
    print(f"workdir of parse: {workdir}")
    return pvo(workdir)

def write_POTCAR(workdir, potcar_paths=None, structure=None, filename="POTCAR", pseudo_set="PBE.54"):
    class PotcarNotGeneratedError(Exception):
        pass

    if potcar_paths is None:
        if structure is None:
            raise PotcarNotGeneratedError("You must specify a structure if you are using default generation!")
        potcar_paths = get_default_POTCAR_paths(structure, pseudo_set=pseudo_set)

    potcar_path = os.path.join(workdir, filename)

    with open(potcar_path, 'wb') as wfd:
        for f in potcar_paths:
            with open(f, 'rb') as fd:
                shutil.copyfileobj(fd, wfd)

    return potcar_path

def write_KPOINTS(workdir, filename="KPOINTS"):
    kpoint_path = os.path.join(workdir, filename)
    with open(kpoint_path, 'w') as f:
        f.write("Automatic mesh\n0\nGamma\n1 1 1\n0 0 0\n")  # Example KPOINTS content
    return kpoint_path

def write_POSCAR(workdir, structure, filename="POSCAR"):
    poscar_path = os.path.join(workdir, filename)
    structure.to(fmt="poscar", filename=poscar_path)
    return poscar_path

def write_INCAR(workdir, incar, filename="INCAR"):
    incar_path = os.path.join(workdir, filename)
    incar.write_file(incar_path)
    return incar_path

@Workflow.wrap.as_function_node("workdir")
def write_VaspInputSet(workdir, structure, incar, potcar_paths=None, kpoints=None):
    _ = write_POSCAR(workdir=workdir, structure=structure)
    _ = write_INCAR(workdir=workdir, incar=incar)
    _ = write_POTCAR(workdir=workdir, structure=structure, potcar_paths=potcar_paths)
    if kpoints is not None:
        _ = write_KPOINTS(workdir=workdir)

    return workdir

class Storage:
    @staticmethod
    def _convert_to_dict(instance):
        attributes = vars(instance)
        result_dict = {key: value for key, value in attributes.items() if "_" not in key[0]}
        return result_dict

class ShellOutput(Storage):
    stdout: str
    stderr: str
    return_code: int

@Workflow.wrap.as_function_node("output")
def run_job(command: str, workdir="test", environment=None, arguments=None):
    if environment is None:
        environment = {}
    if arguments is None:
        arguments = []
    print(f"run_job is in {os.getcwd()}")
    environ = dict(os.environ)
    environ.update({k: str(v) for k, v in environment.items()})
    proc = subprocess.run(
        [command, *map(str, arguments)],
        capture_output=True,
        cwd=workdir,
        encoding="utf8",
        env=environ,
        shell=True,  # Temporary placeholder to simulate "srun vasp_std" with "cp jobdir ."
    )
    print(f"Running job in directory: {workdir}")
    output = ShellOutput()
    output.stdout = proc.stdout
    output.stderr = proc.stderr
    print(proc.stdout, proc.stderr)
    output.return_code = proc.returncode
    return output

@Workflow.wrap.as_function_node("convergence")
def check_convergence(workdir, vaspoutput, filename_vasprun="vasprun.xml", filename_vasplog="vasp.log", backup_vasplog="error.out"):
    converged = False
    line_converged = "reached required accuracy - stopping structural energy minimisation"

    try:
        vr = Vasprun(filename=os.path.join(workdir, filename_vasprun))
        converged = vr.converged
    except:
        try:
            converged = is_line_in_file(filepath=os.path.join(workdir, filename_vasplog), line=line_converged, exact_match=False)
        except:
            try:
                converged = is_line_in_file(filepath=os.path.join(workdir, backup_vasplog), line=line_converged, exact_match=False)
            except:
                pass

    return converged

@Workflow.wrap.as_macro_node("vasp_output", "convergence_status")
def vasp_job(self, workdir, structure, incar, potcar_paths=None):
    self.vaspwriter = write_VaspInputSet(workdir=workdir, structure=structure, incar=incar, potcar_paths=potcar_paths, kpoints=None)
    self.job = run_job(command="module load vasp; module load intel/19.1.0 impi/2019.6; unset I_MPI_HYDRA_BOOTSTRAP; unset I_MPI_PMI_LIBRARY; mpiexec -n 1 vasp_std", workdir=self.vaspwriter)
    self.vasp_output = parse_VaspOutput(workdir="test", output=self.job)#self.vaspwriter)
    self.convergence_status = check_convergence(workdir=self.vaspwriter, vaspoutput=self.vasp_output)
    return self.vasp_output, self.convergence_status
def get_default_POTCAR_paths(structure, pseudo_lib_path="/cmmc/u/hmai/vasp_potentials_54/", pseudo_set="PBE.54"):
    site_element_list = [site.species_string for site in structure]
    element_list = list(dict.fromkeys(site_element_list))  # Remove duplicates and preserve order
    potcar_paths = [os.path.join(pseudo_lib_path, element, "POTCAR") for element in element_list]
    return potcar_paths

# Define INCAR as an example (needs to be adapted to your specific use case)
from pymatgen.io.vasp.inputs import Incar
incar = Incar.from_dict({
    "ENCUT": 520,
    "EDIFF": 1e-4,
    "ISMEAR": 1,
    "SIGMA": 0.1,
})

bulk_Fe = bulk("Fe", cubic=True)
bulk_Fe = AseAtomsAdaptor().get_structure(bulk_Fe)

v_job = vasp_job(workdir="/cmmc/u/hmai/github_dev_pyiron/pyiron_vasp_nodes/test", structure=bulk_Fe, incar=incar)
var1, var2 = v_job.run()
print(v_job.outputs.to_value_dict())
```

Clearly, there is no dependency to specify from the output channels that (I feel) is necessary to specify here, between the individual nodes _except_ for the fact that the node must be finished before the next can run. From example, there's no real reason for me to specify a dummy variable like `workdir=self.vaspwriter`, when all it is saying is that I want this node to run before this one in this macro node, for example, when I write the output, then call the shell node. These two are dependent, but there shouldn't be any output->input linking since the created files are the requirements for running the `shell` node. But the macro node doesn't pull in order of execution, without me doing this. Ideally, I'd like to be able to specify that a node has a dependency on a node _overall_, instead of the creation of a dummy output that is not strictly necessary for the workflow itself.

Any ways around this?

**Comment by liamhuber** [comment]
Yep, you bet! There is a formal separation between the flow of data and the flow of execution -- i.e. we actually have two graphs at all time. This is necessary (as far as I can tell) to facilitate acyclic data flow, but can also be leveraged in situations like this where you want control over the flow even if it is a DAG.

Just like data, execution runs with channels. By default, each node has `.signals.input.run`, `.signals.input.accumulate_and_run`, and `.signal.output.ran`. These allow us to trigger a run when _any_ connection fires, after _all_ connections have fired, and to fire downstream, respectively. There is also some syntactic sugar: `>>` connects `ran` to `run`, while `<<` connects one or more `ran`s to `accumulate_and_run`. I.e. `a >> b >> c; b >> d` makes a forked DAG where after `a` runs `b` then `c` and `d` (which could be in parallel if you were using executors). And `d <<< (a, b, c)` means `a`, `b`, and `c` can all run (potentially in parallel) to start, and then `d` will wait until they're _all_ finished. 

You haven't run into this because in the case of DAGs, `pyiron_workflow` uses the data flow to automatically construct these -- either at run-time for a `Workflow` or at instantiation time for a `Macro`. Try adding a cyclic data flow and you should get a `CircularDependencyError` that tells you the execution can't be automated (I should probably update this to also hint at how to set it manually!). The only real pain-point with this system is that if you explicitly define _any_ element of the execution flow, your macro needs to define the _entire_ execution flow (_and_ starting nodes!). I.e. you can't mix and match the automated data DAG analysis with explicit definition.

So, concretely, you could re-write `vasp_job` without passing around `workdir` as:

```python
@Workflow.wrap.as_macro_node("vasp_output", "convergence_status")
def vasp_job(self, workdir, structure, incar, potcar_paths=None):
    self.vaspwriter = write_VaspInputSet(workdir=workdir, structure=structure, incar=incar, potcar_paths=potcar_paths, kpoints=None)
    self.job = run_job(command="module load vasp; module load intel/19.1.0 impi/2019.6; unset I_MPI_HYDRA_BOOTSTRAP; unset I_MPI_PMI_LIBRARY; mpiexec -n 1 vasp_std")
    self.vasp_output = parse_VaspOutput(workdir="test", output=self.job)
    self.convergence_status = check_convergence(vaspoutput=self.vasp_output)

    self.vaspwriter >> self.job >> self.vasp_output >> self.convergence_status
    self.starting_nodes = [self.vaspwriter]

    return self.vasp_output, self.convergence_status
```

An alternative attack would be to re-frame your function nodes to convert the flow of information you have ("I'm running `run_job` therefore I've written the right files to `workdir`") into a flow of data. One attack would be to have `run_job` explicitly but optionally take paths for each of the four input files. If these paths are non-`None`, it first `cp`s these files into `workdir` then proceeds. (On bash at least, if they're already there bash at least just doesn't copy and continues, which is fast.) Not only does this resolve your flow problem, as now your macro has (in this case redundant, but whatever) data to pass from `write_VaspInputSet` to `run_job`, but it also makes `run_job` more useful in other contexts. E.g. consider the case where you have some large structure with many species which you want to evaluate with multiple kpoint sets or something; imagine the structure/POTCAR are so big that the writing process is not trivially fast -- then writing these files once and `cp`ing them is going to save some time compared to to writing them from scratch each time. To be fair, VASP is _so slow_ that this is a poor example and leveraging the `run_vasp` macro to re-write the files from scratch is unlikely to ever make a big relative cost increase. But the principle is sound, that being more explicit about the IO of the component nodes makes it easier to break them apart and use them in other macros later.
