### ISSUE TITLE
Operating on macro inputs is weird (?)

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_workflow#394]
Consider:
```python
@Workflow.wrap.as_macro_node("vasp_output", "convergence_status")
def vasp_job(self, workdir: str, structure, incar, potcar_paths=None):
    # Check if workdir exists
    workdir_string = str(workdir)
    if not os.path.exists(workdir_string):
        os.makedirs(workdir_string)
    else:
        warnings.warn(f"Directory '{workdir_string}' already exists. Existing files may be overwritten.")

    self.vaspwriter = write_VaspInputSet(workdir=workdir, structure=structure, incar=incar, potcar_paths=potcar_paths, kpoints=None)
    self.job = run_job(command="module load vasp; module load intel/19.1.0 impi/2019.6; unset I_MPI_HYDRA_BOOTSTRAP; unset I_MPI_PMI_LIBRARY; mpiexec -n 1 vasp_std", workdir=workdir)
    self.vasp_output = parse_VaspOutput(workdir=workdir)
    self.convergence_status = check_convergence(workdir=workdir)

    self.vaspwriter >> self.job >> self.vasp_output >> self.convergence_status
    self.starting_nodes = [self.vaspwriter]
    return self.vasp_output, self.convergence_status
```

Is operating directly on function input args like normal python not supported?

What is the right way to do this?

`workdir_string` is `/cmmc/u/hmai/github_dev_pyiron/pyiron_vasp_nodes/vasp_node_job.py:136: UserWarning: Directory 'workdir (UserInput):
Inputs ['user_input']
OutputsWithInjection ['user_input']
InputSignals ['run', 'accumulate_and_run']
OutputSignals ['ran']' already exists. Existing files may be overwritten.`

**Comment by liamhuber** [comment]
This is not a bug, and is deep workflow magic.

Macro nodes are fundamentally different from function nodes, and their signature is meant only to provide a convenient interface to the input channels of child nodes. There are _some_ operations you can do on them: all of those that are supported by node injection (`+`, `*`, etc.).

Here you've mixed and matched function node behaviour with macro node behaviour. The macro-decorated functions run only at instantiation of the macro, not at runtime, so it's actually good that this returns such a bad error, otherwise you would only be checking the initial value! (Node injection operations are an exception, because we literally inject extra nodes which get re-run on every runtime.)

The solution is to node-ize the snippet you are currently using as in-line python calls:

```python
@Workflow.wrap.as_function_node("directory")
def EnsureWorkingDirectory(workdir: str) -> str:
    # Check if workdir exists
    workdir_string = str(workdir)
    if not os.path.exists(workdir_string):
        os.makedirs(workdir_string)
    else:
        warnings.warn(f"Directory '{workdir_string}' already exists. Existing files may be overwritten.")
    return workdir_str

@Workflow.wrap.as_macro_node("vasp_output", "convergence_status")
def vasp_job(self, maybe_workdir: str, structure, incar, potcar_paths=None):
    self.workdir = EnsureWorkingDirectory(maybe_workdir)
    self.vaspwriter = write_VaspInputSet(workdir=self.workdir, structure=structure, incar=incar, potcar_paths=potcar_paths, kpoints=None)
    self.job = run_job(command="module load vasp; module load intel/19.1.0 impi/2019.6; unset I_MPI_HYDRA_BOOTSTRAP; unset I_MPI_PMI_LIBRARY; mpiexec -n 1 vasp_std", workdir=workdir)
    self.vasp_output = parse_VaspOutput(workdir=self.workdir)
    self.convergence_status = check_convergence(workdir=self.workdir)

    self.workdir >> self.vaspwriter >> self.job >> self.vasp_output >> self.convergence_status
    self.starting_nodes = [self.vaspwriter]
    return self.vasp_output, self.convergence_status
```

The key thing to remember is that function nodes invoke the wrapped function at each `.run`, while macro nodes invoke the wrapped function once at instantiation to build a graph and then run that graph at each `.run`. They look similar -- intentionally as similar as we could make them, in fact -- but they are different.
