### ISSUE TITLE
Getting nodes and edges of a workflow 

### ISSUE THREAD

**Issue by JNmpi** [pyiron/pyiron_workflow#409]
Hi @liamhuber, I am looking for a simple approach to extract from a workflow the nodes and edges. I have the following scenarios in mind:

- Defining nodes and explicitly connecting them:

      engine = Workflow.create.atomistic.engine.ase.M3GNet()
      structure = Workflow.create.atomistic.structure.build.bulk('Pb', cubic=True)
      elastic = Workflow.create.atomistic.property.elastic.elastic_constants(structure=structure, engine=engine) 

- Defining a workflow:

      wf = Workflow('compute_elastic_constants')
      wf.engine = wf.create.atomistic.engine.ase.M3GNet()
      wf.structure = wf.create.atomistic.structure.build.bulk('Pb', cubic=True)
      wf.elastic = wf.create.atomistic.property.elastic.elastic_constants(structure=structure, engine=engine) #, parameters=parameters)
      out = elastic.pull()

For the second case getting the nodes is easy, i.e., via `wf.children.items()`. What is the recommended way to get the edges? A related question: If I have the edges, what is the best way to dynamically link the node input and output?

**Comment by liamhuber** [comment]
Hi @JNmpi, I'm afraid I'm not clear on the question.

Your first example is absolutely fine. Your second example is non-compiling as `structure`, `engine`, and `elastic` are not defined. If I clean up these little syntax things, it is also fine:

```python
from pyiron_workflow import Workflow

Workflow.register("pyiron_nodes.atomistic", "atomistic")

wf = Workflow('compute_elastic_constants')
wf.engine = wf.create.atomistic.engine.ase.M3GNet()
wf.structure = wf.create.atomistic.structure.build.bulk('Pb', cubic=True)
wf.elastic = wf.create.atomistic.property.elastic.elastic_constants(
    structure=wf.structure, 
    engine=wf.engine
) #, parameters=parameters)
out = wf.elastic.pull()
```

Is your question getting at the idea of how to post-facto "parent" your first example so that all the nodes live in a workflow like the second example? You can do that with the `topology` sub-module, but it's not clear to me that this is really super useful...

```python
from pyiron_workflow import Workflow

Workflow.register("pyiron_nodes.atomistic", "atomistic")

engine = Workflow.create.atomistic.engine.ase.M3GNet()
structure = Workflow.create.atomistic.structure.build.bulk('Pb', cubic=True)
elastic = Workflow.create.atomistic.property.elastic.elastic_constants(structure=structure, engine=engine) 

wf = Workflow("late_parent")

from pyiron_workflow.topology import get_nodes_in_data_tree

for n in get_nodes_in_data_tree(elastic):
    n.parent = wf

out = wf.elastic_constants.pull()
```

Other than the names of the child nodes, the `wf` in these two examples are perfectly equivalent.

> For the second case getting the nodes is easy, i.e., via `wf.children.items()`. What is the recommended way to get the edges? 

You can make a compound-list for each child, for each input channel, for each connection. Jan was asking about this a couple weeks ago, so I made a convenience function that does this and returns graph data as a dictionary (#399). The dictionary has "nodes", and "edges", where "edges" are further decomposed into "data" and "signal". The "nodes" is just a plain dictionary coupling the full label to the child instance, but the edges have tuples as keys with the labels of both sides of the connection, i.e. `tuple[str, str]: tuple[OutputDataWithInjection, InputData]`. E.g., to look at all the connections in the example above:

```python
for (out, inp) in wf.graph_as_dict["edges"]["data"].keys():
    print(out, "-->", inp)
>>> /compute_elastic_constants/engine.engine --> /compute_elastic_constants/elastic.engine
>>> /compute_elastic_constants/structure.structure --> /compute_elastic_constants/elastic.structure
```

> A related question: If I have the edges, what is the best way to dynamically link the node input and output?

In what format do you have the edges? What does dynamically mean? As soon as you have the desired channel objects in python, you can always form a connection via `input_object = output_object`, `input_object.connect(output_object)`, or `output_object.connect(input_object)`. (Aside: multiple connections are totally allowed, with newer connections take priority over older connections, where `InputData.fetch()` looks through connections and takes the first one holding something other than `NOT_DATA` and uses that to update its `value`.)

**Comment by JNmpi** [comment]
Thanks @liamhuber for the quick reply. Very helpful. It looks straightforward and I will try it today evening.
