### ISSUE TITLE
injection makes it difficult to see what's defined and what's not

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_workflow#487]
I find it difficult to understand that when I run `MyNode.children`,  `pyiron_workflow` injects a node `children`, while I have not assigned anything at this point. Especially, I find it confusing when there is `MyMacroNode.children` which has a totally different meaning than `MyNode.children`. Also, when I draw the workflow there's a new node appearing even though I didn't assign anything there. That's confusing.

Is there a particular reason that it has to be defined on the `__getattr__` level? Can't we define another function for this?

**Comment by liamhuber** [comment]
Do you actually find it difficult to understand, or just annoying?

If you are legitimately misunderstanding, I can lay out the chain of events pretty easy: We use node-injection on output channels as a shortcut so you don't need to explicitly instantiate nodes for each operation, e.g. you can just add two node channels to introduce a new node that (in a delayed way) adds their values. Similarly with attribute access, if `MyNode` has an output channel `foo: Foo`, and `Foo` instances in turn have an attribute `bar`, then for `some_node: MyNode` we can conveniently write and work with `some_node.outputs.foo.bar`. This saves loads of time and makes it feel more pythonic.
On top of this, each node that has _only_ one output value, will fall back on trying operations on that output -- i.e. in the example before, if `foo` was the _only_ output of `MyNode`, we could just write `my_node.bar`. So, as it pertains to your example, `MyMacroNode.children` finds the existing `children` attribute from `Macro` inheritance, while `MyNode.children` falls back on trying to inject a node. This raises an exception, because the node injections try to automatically run on instantiation, but if the root node (`some_node`) had a parent, then by then it's too late -- the injected node has already been added to the parent.

If you just find it annoying... that is fair. I don't have any intention of getting rid of either node injection nor the single-output behaviour. I also lean against getting rid of injection for attribute access _in particular_, but there at least I'm open to a persuasive argument.

If the injected node raises an error when it automatically runs, I could get behind the idea that is should then be automatically removed from any parent it now belongs to. Of course, this should only happen at the initial auto-run -- we don't want nodes deleting themselves all over the place in some even that you feed bad data through the graph. I can imagine that such a solution is possible, e.g. injected nodes inherit from some new class, and that new class modifies the initialization with some extra `have_i_autorun_yet` flag, and when you fail _and_ that flag is `False`, then you check if you have a parent, and if you do then you delete yourself from that parent... I'm not totally closed to such an attack, but I don't know if I like that much better.

**Comment by samwaseda** [comment]
Difficult to understand. Actually in the sense of confusing. Let's take this one as an example:

```python
wf = Workflow("wf")
wf.my_int = Workflow.create.standard.UserInput(42)
print(wf.my_int.hello)
wf()
```

This one fails, because the injection created a new node `hello`. This behaviour is particularly confusing, because it implicitly creates a new node, while I'm neither calling a function nor assigning an attribute.

Furthermore, it blurs the distinction between nodes and values, as well as what to expect from an operation:

```python
wf = Workflow("wf")
wf.my_int = Workflow.create.standard.UserInput(42, autorun=True)
(wf.my_int < 50).value
```

This code might deliver you `True`, but it gives me more headache because this makes `wf.my_int` neither really a node, nor a value, because it would basically mean "an operation on a node returns a node with the value the operation is applied on and at the same time appends the node to the workflow". I see the convenience, but it makes the initial hurdle extremely high.

A possible solution that I would accept would be to not inject a node implicitly, i.e. the  code just above (with `wf.my_int < 50`) should work but **does not** append a node into `wf`, and if the user wishes, especially when it's delayed, then they have to explicitly assign it:

```python
wf = Workflow("wf")
wf.my_int = Workflow.create.standard.UserInput(42, autorun=True)
wf.comparison = wf.my_int < 50
```

This already does what I think it should do. It's still not quite straightforward, but at least the operation won't be implicit.

**Comment by samwaseda** [comment]
Your example now convinced me: The whole injection thing must not exist.

The very reason why people write workflows is not because it makes numerical operations simpler, but because it makes the steps clearer and well defined, in particular scientifically in our case. Your example creates bunch of steps in the workflow, which make it extremely difficult to understand what was actually done, both in the diagram with `draw` and when we want to capture the actual physics. The correct thing to do is:

```python
from pyiron_workflow import Workflow, standard_nodes as std, function_node

def my_well_defined_function(array):
    result = array[-1] / (array[0] + array[-1])
    return result

wf = Workflow("injected")
wf.inp = std.UserInput([1, 2, 3, 4])
wf.math = function_node(my_well_defined_function, wf.inp)
wf()
```

Is this more code? Yes, somewhat. Is this too much code? No it definitely isn't. Instead, this injection thing creates a whole range of fatal problems:

- Conceptual problems:
  - It creates nodes **implicitly**
  - Operations on nodes have different meanings depending on which one (`==`, `<<`, `>>` on nodes while `+`, `-`, `*` etc. on their values)
- Technical problems
  - It adds a lot of lines for maintenance
  - It makes the whole workflow extremely difficult to understand (cf. `wf.draw()` of your example)
  - It makes it even more difficult for new users to use `pyiron_workflow`

So in the end not only not it's not free lunch, but it feels to me like we're paying a lot of money to ask to put salt in my coke.

**Comment by liamhuber** [comment]
Yep, your arguments are perfectly reasonable, and removing it entirely is an outcome I can accept. I still don't _want_ to remove it, but I am willing to.

Next you need to convince @JNmpi that the more verbose path is preferable. If you both come to consensus, I'm open to a clean removal of the feature.

**Comment by liamhuber** [comment]
That was my understanding. I don't have time for it imminently, but something I would like is maybe to hide it behind a global-state feature flag, or at least do some refactoring so that removing the feature is even easier in the future if that's what's wanted.
