### ISSUE TITLE
TOC is broken in documentation

### ISSUE THREAD

**Issue by XzzX** [pyiron/pyiron_workflow#500]
https://pyiron-workflow.readthedocs.io/en/latest/source/examples.html

There should only be three notebooks and captions underneath.

**Comment by liamhuber** [comment]
Good catch. At somepoint I added `# Subsections` to the quickstart as markdown cells instead of `## Subsections`, so the parser is (sensibly) putting them at the top level of the ToC. I've got a local branch that should fix it, but I need to find 10 minutes to go and renew my GPG key before pushing. I might not fix it "soon", but it will be the next code thing I do.

**Comment by liamhuber** [comment]
Fixed in #511
