### ISSUE TITLE
New release?!

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_workflow#506]
I would like to have a new release before monday to allow pint to update on the cluster. Would that be possible @liamhuber ?

**Comment by liamhuber** [comment]
@niklassiemer: [Done](https://github.com/pyiron/pyiron_workflow/releases/tag/pyiron_workflow-0.11.1) 👍 

Do you also use `pyiron_ontology` in that environment? Because there I got stuck in the [pyiron dependency hell](https://github.com/pyiron/pyiron_ontology/pull/72) and then haven't gotten back to it for a couple months (I checked since the last comment, but the numpy problem still existed). There we also [need a pint update](https://github.com/pyiron/pyiron_ontology/pull/79)

**Comment by niklassiemer** [comment]
Thanks a lot,

No ontology does not yet have a production use case. Thus, it is not (yet) in the cmti environment. The cmti environment is actually build in the docker-stacks :)
