### ISSUE TITLE
Disable type checking

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_workflow#521]
I've been working on ontological types, and now I would like to be able to do something like:

```python
class VacancyStructure(Atoms):
    pass

def create_structure(element: str) -> Atoms
    ...
    return structure

def create_vacancy(structure: Atoms) -> VacancyStructure:
    vac = VacancyStructure(structure)
    del vac[0]
    return vac

def relax_structure(structure: Atoms) -> Atoms:
    ...
    return structure

def calculate_vacancy_formation_energy(vacancy_structure: VacancyStructure) -> float:
    ...
    return vacancy_formation_energy
```

So the problem is obviously the step `create_vacancy` -> `relax_structure` -> `calculate_vacancy_formation_energy`, since for `relax_structure` the structure doesn't matter, while it matters very much for `calculate_vacancy_formation_energy`. In this regard, the best would be to be able to plug-in a custom-made validator, but for my purpose right now it would suffice if the pyiron_workflow internal validator is turned off. From what I can see in the code, that's not possible, right? Do you think I can simply create a new argument `disable_type_checking`, so that I could write something like this?

```python
vacancy_structure = create_vacancy()
relaxed_structure = relax_structure(structure=vacancy_structure, disable_type_checking=True)
vacancy_formation_energy = calculate_vacancy_formation_energy(vacancy_structure=relaxed_structure, disable_type_checking=True)
```

**Comment by samwaseda** [comment]
(I forgot to put the decorators)

**Comment by samwaseda** [comment]
ok I just realized that my idea wouldn't work because the input setting is done via `__setitem__` and `__setattr__`.

**Comment by liamhuber** [comment]
First and foremost: there are a few routes for deactivating the type hinting. I'm open to improving the UX, but I think the functionality is pretty reasonable:

```python
import pyiron_workflow as pwf

@pwf.as_function_node
def AddOne(x: int) -> int:
    return x + 1

    
n = AddOne()

# Option 1) easy but broad: deactivate all hints on a node (recursively for macros)
# n.deactivate_strict_hints()

# Option 2) Precise but time consuming: deactivate hints on a per-channel basis
# n.inputs.x.strict_hints = False
# n.outputs["x + 1"].strict_hints = False  # in our example output was hinted too!

# Option 3) TERRIBLE IDEA: manually remove the hint
# n.inputs.x.type_hint = None
# n.outputs["x + 1"].type_hint = None

# Will fail without at least one type hint checking modification above:
n(4.5)
```

In this case we _could_ add a new init kwarg like `disable_type_checking` which just invokes `self.deactivate_strict_hints()` in the initialization, but I don't feel it's a big advantage over just calling it afterwards, and it will be slightly more to maintain.

Second, note that if `VacancyStructure` inherits directly from `Atoms`, you won't need to mess with the type checking for your `relaxed_structure_node`. The type checking works on a ["as-or-more specific"](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L37) basis, so `relax_structure` is willing to return a subclass of `Atoms`.

Third, we now see why Joerg came up with the idea of transitive ontological properties and why I want to keep type hints (data format) and ontological hints (data meaning) on separate paths --  `relax_structure` cares about getting something in the `ase.Atoms` _format_, but doesn't care a whit what sort of ontological distinctions that structure carries. Meanwhile, `calculate_vacancy_formation_energy` is _also_ looking for something that has the data format of `Atoms` (I guess it's a macro that's internally it's just doing static energy calculations with other nodes that, like the relaxation, don't care about ontological information of the structure they're calculating), and it's content to get something relaxed, but somehow we need a way to "carry" the information that this structure with `ase.Atoms` format was originated in a "vacancy"-producing way ontologically speaking. I find it more elegant to thus keep the data format and ontological information connected but distinct; I'm open to exploring a unified approach suggested by `VacancyStructure`, I have a gut suspicion it will wind up being less powerful.

**Comment by liamhuber** [comment]
Ah, I forgot to say, having the validator be modular and replaceable is a neat idea. I don't think there's any fundamental barrier to doing that; from what I can see it would just be going into `pyiron_workflow.channels`, looking for the usages of these:

https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/channels.py#L19-L22

And then making sure users can swap out the functions used instead of hard coding them to these imports. As far as I see/remember, the type checking is all encapsulated to happen right in the channels module so that would be it.

**Comment by samwaseda** [comment]
But the following code doesn’t work? (With or without `deactivate_strict_hints`)

```python
from pyiron_workflow import Workflow
from ase import Atoms

class VacancyStructure(Atoms):
    pass

@Workflow.wrap.as_function_node
def create_vacancy(structure: Atoms) -> VacancyStructure:
    structure = VacancyStructure(structure)
    structure.pop(0)
    return structure

@Workflow.wrap.as_function_node
def relax_structure(structure: Atoms) -> Atoms:
    return structure

@Workflow.wrap.as_function_node
def get_vacancy_formation_energy(structure: VacancyStructure) -> float:
    return 0.0

wf = Workflow("test")
wf.vacancy = create_vacancy()
wf.vacancy.deactivate_strict_hints()
wf.relaxed = relax_structure(structure=wf.vacancy)
wf.relaxed.deactivate_strict_hints()
wf.formation_energy = get_vacancy_formation_energy(structure=wf.relaxed)
wf.formation_energy.deactivate_strict_hints()
```

**Comment by samwaseda** [comment]
The problem is [here](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/io.py#L99-L103). Depending on whether the input is a value or a channel, `_assign_value_to_existing_channel` does something very different. I have the feeling that type checking should be the step before this if-statement. What do you think?

**Comment by liamhuber** [comment]
I'll need to wait until O can run your example (I'm on mobile now). I wouldn't expect the graph to actually run, because I don't think the vacancy class will let you do those things, but I do expect all the connections to work.

I also don't see things going wrong where you claim -- we can't do the type checking until we figure out if we should be checking the type of the new value, or the type hint of the new value (because it's another channel), but in both cases it looks to me (again, skimming on mobile) like the check is correctly being done in both cases, including just passing an "OK" if the input channel I has been instructed to not check types.

So naively, I would expect your example above to build a graph and if it doesn't either I've misunderstood something or there's an actual bug.

**Comment by liamhuber** [comment]
Ah, no, your example should fail. The relax structure guy only promises to return `Atoms` but the calculate vacancy energy guy expects a `VacancyStructure`. You need to instantiate the energy calculator, deactivate its type hints, and _then_ connect the relaxed structure.

To get it to work entirely without deactivating hints we need some sort of transitive type narrowing that happens at run-time. Ironflow does this with the ontology, but there's zero mechanism for that sort of thing here. Implementing such a thing is on my list of proposed work I gave to Tilmann.

**Comment by samwaseda** [comment]
So from my point of view, there should be two things that should be done:

1. `_assign_a_non_channel_value` and `connect` should use the same validator
2. The validator should be modular to be able to be replaced by the user.

We’ve sort of agreed on the second point. What do you think of the first one?

**Comment by liamhuber** [comment]
1)

`_assign_a_non_channel_value` is just a simple wrapper, we need to look directly at the `Channel` objects. Here there is the `value` setter and the `connect` method. Let's walk through what's actually happening in these, as I need to refresh myself anyway:

The `value` setter redirects to [`DataChannel._type_check_new_value`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/channels.py#L361-L366), which is doing some simple flag checking and leveraging [`pyiron_workflow.type_hinting.valid_value`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L14-L27) (the `InputData` overrides and does extends this a bit, but nothing we need to worry about here). This does some reformatting (in case the value carries units), then uses straight python `isinstance`, _then_ falls back on `typeguard.check_type` to compare the new value instance to the type hint.

Meanwhile, `Channel.connect` does a few things, but the relevant bit for us is the validity check, which [for `DataChannel`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L14-L27) needs to handle a variety of hinted/unhinted/hints on/off cases. At the end of the day, if the hint checking is on and both sides of the connection are hinted, we leverage [`pyiron_workflow.type_checking.type_hint_is_as_or_more_specific_than`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L37-L100) to compare the two hints (i.e. a class-vs-class comparison, instead of instance-vs-class comparison. AFAIK there is no mainstream tool to account for this, although python provides the tools in builtins to break apart composite hints etc...this is all the hand-coded logic in the method we have here. TBH I'm not even 100% confident it will always work, I just have proof-by-lack-of-imagination that my implementation hasn't failed yet.

So what could we do to "use the same validator"? Well, we can't get `connect` to rely on what the `value` setter does, because we need custom hint-vs-hint comparisons, not a value-vs-hint check that can be found in other libraries. We might make progress the other way around -- instead of using [`typeguard.check_type`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L23C13-L23C23), I bet we could instead use `type_hint_is_as_or_more_specific_than(value.__class__, self.type_hint)`. We'll need to check, but I don't see why this would fail.

Of course, that doesn't mean that `connect` and `value` can just look the same -- we still need different wrappers _around_ the underlying validator to handle different cases (stripping a `Quantity` instance down, seeing if we've asked for checks at all, seeing if our connection partner even has a hint, etc.). Going to this work makes sense iff we want to allow custom validators, otherwise `typeguard.check_type` is totally fine for the value setter.

2)

I agree it would be fun, but I don't know if it's worth the effort. If I understand your motivation, it's so we can convolute type checking with "ontological checking" in the same process. My gut still tells me it will be wiser to leave the format type checking and ontological type checking as independent as possible. In this case we could basically leave the (totally functioning) type checking alone and layer a second o-type checking system on top of it. Barring some good argument for why convoluting the two checks will be superior, I would start implementing the independent o-type system relying on `semantikon`-hinted channels if/when I get a signed contract back.

**Comment by liamhuber** [comment]
> `_assign_a_non_channel_value` is just a simple wrapper, we need to look directly at the `Channel` objects. Here there is the `value` setter and the `connect` method. Let's walk through what's actually happening in these, as I need to refresh myself anyway:
> 
> The `value` setter redirects to [`DataChannel._type_check_new_value`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/channels.py#L361-L366), which is doing some simple flag checking and leveraging [`pyiron_workflow.type_hinting.valid_value`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L14-L27) (the `InputData` overrides and does extends this a bit, but nothing we need to worry about here). This does some reformatting (in case the value carries units), then uses straight python `isinstance`, _then_ falls back on `typeguard.check_type` to compare the new value instance to the type hint.
> 
> Meanwhile, `Channel.connect` does a few things, but the relevant bit for us is the validity check, which [for `DataChannel`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L14-L27) needs to handle a variety of hinted/unhinted/hints on/off cases. At the end of the day, if the hint checking is on and both sides of the connection are hinted, we leverage [`pyiron_workflow.type_checking.type_hint_is_as_or_more_specific_than`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L37-L100) to compare the two hints (i.e. a class-vs-class comparison, instead of instance-vs-class comparison. AFAIK there is no mainstream tool to account for this, although python provides the tools in builtins to break apart composite hints etc...this is all the hand-coded logic in the method we have here. TBH I'm not even 100% confident it will always work, I just have proof-by-lack-of-imagination that my implementation hasn't failed yet.
> 
> So what could we do to "use the same validator"? Well, we can't get `connect` to rely on what the `value` setter does, because we need custom hint-vs-hint comparisons, not a value-vs-hint check that can be found in other libraries. We might make progress the other way around -- instead of using [`typeguard.check_type`](https://github.com/pyiron/pyiron_workflow/blob/913a03f9a4c8933e944366d1efc5d1dad1b8ae83/pyiron_workflow/type_hinting.py#L23C13-L23C23), I bet we could instead use `type_hint_is_as_or_more_specific_than(value.__class__, self.type_hint)`. We'll need to check, but I don't see why this would fail.
> 
> Of course, that doesn't mean that `connect` and `value` can just look the same -- we still need different wrappers _around_ the underlying validator to handle different cases (stripping a `Quantity` instance down, seeing if we've asked for checks at all, seeing if our connection partner even has a hint, etc.). Going to this work makes sense iff we want to allow custom validators, otherwise `typeguard.check_type` is totally fine for the value setter.
> 
> 
> I agree it would be fun, but I don't know if it's worth the effort. If I understand your motivation, it's so we can convolute type checking with "ontological checking" in the same process. My gut still tells me it will be wiser to leave the format type checking and ontological type checking as independent as possible. In this case we could basically leave the (totally functioning) type checking alone and layer a second o-type checking system on top of it. Barring some good argument for why convoluting the two checks will be superior, I would start implementing the independent o-type system relying on `semantikon`-hinted channels if/when I get a signed contract back.



So overall, I don't hate the idea of refactoring things to use the same validator at end of the line. Some speed checks vs the typeguard implementation would be wise, but otherwise it makes sense to be using the same tool. But after that I'm not hugely motivated to make use of that by modifying the type checker, I'd rather leave the working thing working and add an independent thing alongside it.

**Comment by samwaseda** [comment]
So following our meeting on Monday, we'll try to explore the possibility of applying ontological validators, which tangentially solves the problem that I had, so I close this issue.
