### ISSUE TITLE
Inconsistent diagram for macro node

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_workflow#56]
```python
from pyiron_workflow.function import single_value_node
from pyiron_workflow import Workflow

@single_value_node()
def adder(a, b=1):
    result = a + b
    return result

@single_value_node()
def multiplier(a, b=2):
    result = a * b
    return result

@Workflow.wrap_as.macro_node()
def add_multiply(macro):
    macro.add(adder(a=2))
    macro.add(multiplier(a=macro.adder))

wf = Workflow("arithmetic")
wf.add(add_multiply())
wf.draw(depth=2)
```
Above code produces the following diagram:

<img width="1080" alt="Screenshot 2023-10-30 at 14 23 47" src="https://github.com/pyiron/pyiron_workflow/assets/37879103/fc829163-ba86-46c1-83eb-387886e7a91d">

I would have expected arrows from `adder__a` to `a` (and other inputs), as well as `result` to `multiplier__result` inside macro node. Was this meant to be like this?

**Comment by liamhuber** [comment]
Your expectation is good and it was meant to be like this. The arrows are only drawn along connections, and connections can only be made between input and output.

When I made macros have their own io instead of just holding a reference to their children's io, I introduced a new feature where io can be "linked" to one other channel of the _same type_. For persistence when children are shipped off to an executor, these links need to be held by the outermost scope (ie the macro channels not the child channels). What they represent is that the `value` of the child/macro input/output channel gets updated whenever the value of the macro/child input/output gets updated, ie they stay in sync.

I did not yet add any code to the draw call to reflect these links. I guess a dashed orange arrow would be nice. It should've perfectly doable and I agree it's necessary, I just never thought of it.
